version: '3.8'

services:
  theone-app:
    build: .
    container_name: theone-dating-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - APP_NAME=theOne - AI Dating
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_URL=sqlite:///./theone_production.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GPT_MODEL=gpt-4o-mini
      - EMBEDDING_MODEL=text-embedding-3-small
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
    volumes:
      - ./data:/app/data
      - ./static/uploads:/app/static/uploads
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: theone-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - theone-app
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
  uploads:
  logs:
